### ISSUE TITLE
Provide minimal image for build only

### ISSUE THREAD

**Issue by daincredibleholg** [AdoptOpenJDK/openjdk-virtual-images#42]
Hi.

I just started to look into the OpenJDK image creation process. I was wondering why we wanna have a full blown VM (with X (or equivalent), a Window Manager, an IDE...) only. What I would like to have is a VM which just provides the minimal requirements to build the JDK and provides a shared folder with the code. This would let me use my IDE natively on my system (in this case it would be MacOS). At the end this should bring some benefits like not fiddling around with different key bindings (MacOS wants CMD+C for copying stuff, rest of the world uses CTRL+C and CMD+C is also a shortcut in VirtualBox which changes the view mode (THAT is annoying)). The IDE should also run a little bit more stable and we do not have the legal implications (e.g. distributing IntelliJ).

Disclaimer: I do completely agree that we need a "all-inclusive" box to make it easier to start. But with the tooling (packer.io, Vagrant, Chef / Puppet) we can hopefully find a way to maintain different kinds of environments.

What are your ideas? Does this makes sense?

**Comment by neomatrix369** [comment]
Have you seen this

Build your own light-weight VM
<http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/content/virtual-machines/build_your_own_lightweight_vm.html>

in our Adopt OpenJDK - Getting Started Kit
<http://neomatrix369.gitbooks.io/adoptopenjdk-getting-started-kit/content/>
 gitbook?

Cheers,
Mani

**Comment by daincredibleholg** [comment]
Hi @neomatrix369.

Yes and I am trying to get this up and running. The question was more about if there is an interest of having this kind of image "officially" available. And yes, I am happy to keep on working on this. (Although I have a couple of issues building the image as described on the given links, but I will try and, if needed, open other issues for it.)

And thanks for your reply :)

**Comment by daincredibleholg** [comment]
Hi again.

Ok, forget what I've said. It would be easier, if I would just click on the links before answering instead of just looking on the links... Sorry again.

Anyway, I am trying to get the scripts to work again. Is there anyone else working on that?

Cheers and sorry again :-D

**Comment by neomatrix369** [comment]
Atm the moment no one is working on it, so take your jab at it.

Cheers,
Mani
